# pages/findings.py
from dash import html, dcc
from app import dash

dash.register_page(__name__, path="/findings")

layout = html.Div(className="page-container findings-page", children=[

    # Page title
    html.H2("Major Findings for EV Growth", className="section-title"),

    # 1) EV Sales (IEA)
    html.Div(className="findings-section", children=[
        html.H3("EV Sales in USA (IEA)", className="subsection-title"),
        html.Div(className="media-wrapper", children=[
            html.Img(
                src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/EV_sales_USA_2010-2023IEA.png",
                className="full-image"
            ),
            html.Div(className="findings-text", children=[
                "In this plot generated by ",
                html.A(
                    "IEA",
                    href="https://www.iea.org/data-and-statistics/data-tools/global-ev-data-explorer",
                    target="_blank",
                    className="source-link"
                ),
                ", we can see that the number of EV sales has grown exponentially over the years in the USA."
            ])
        ])
    ]),

    # 2) US EV Energy History
html.Div(className="findings-section", children=[

    # Section subtitle + side-by-side panels
    html.H3("United States EV Energy History", className="subsection-title"),
    html.Div(className="media-wrapper", children=[
        html.Img(
            src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/april29-results/US_energy_usage_growth.png",
            className="half-image"
        ),
        html.Img(
            src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/april29-results/US_charging_session_growth.png",
            className="half-image"
        )
    ]),
    html.Div(className="findings-text", children=[
        "Summary: The left plot shows energy usage history; the right plot shows charging session history. "
        "Both charging session and energy usage are increasing linearly over time for all regions combined in the USA. "
        "The monthly growth rate of energy usage on avg is 5.45% per month, while the monthly growth for charging sessions is 4.88%."
    ]),
]),
    # 3) Pacific region analysis
    html.Div(className="findings-section", children=[

        html.H3("Further Analysis With Focus on the Pacific Region", className="subsection-title"),
        # Centered Info line, tight to the chart
        html.P(
            "(Info: History of charging sessions and energy usage in the Pacific region.)",
            className="info-text"
        ),
        html.Div(className="media-wrapper", children=[
        html.Img(
            src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/april29-results/Pacific_energy_usage_growth.png",
            className="half-image"
        ),
        html.Img(
            src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/april29-results/Pacific_charging_session_growth.png",
            className="half-image"
        )
    ]),
        # Summary text
        html.Div(className="findings-text", children=[
            "Summary: This plot focuses on comparing charging sessions and energy usage in the Pacific region. "
            "Something interesting we found, is that the pacific region has an exponential growth rate, where the exponential "
            "model fitted better than linear with a r2 score of 0.952 for energy usage and 0.904 for sessions. This suggest that the pacific region "
            "is experiencing exponential growth in usage and sessions. While the monthly growth rates we got for charging sessions was approximately "
            "3.86% and 4.37% for energy usage on avg."
        ])
    ]),


    # 4) Popular charging locations
html.Div(className="findings-section", children=[

    html.H3("Popular Charging Locations in the Pacific Region", className="subsection-title"),

    # 4a) Top locations bar chart
    html.Div(className="media-wrapper", children=[
        html.Img(
            src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/april29-results/pacific_popular_locations.png",
            className="full-image"
        )
    ]),
    html.P(
        "(Info: Charging session counts by location.)",
        className="info-text"
    ),
    html.Div(className="findings-text", children=[
        "Summary: This plot shows the top charging locations in the pacific region. "
        "We can see that over time, Portland-Vancouver-Hillsboro is the most popular location, "
        "comparing the growth rates, we found that Portland-Vancouver-Hillsboro, Seatle-Tacoma-Bellevue, and Salem has "
        "exponential trend, while Los Angeles-Long Beach-Anaheim has a linear trend. Avg monthly growth rates in the plot."
    ]),

    # 4b) Heatmap of top areas
    html.Div(className="media-wrapper", children=[
        html.Img(
            src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/april29-results/OR_WA_heatmap.png",
            className="full-image"
        )
    ]),
    html.P(
        "(Info: Heatmap visualization of growth.)",
        className="info-text"
    ),
    html.Div(className="findings-text", children=[
        "Summary: The heatmap is just used as another visualization to show growth, here we chose the top location. "
        "The heatmap focuses on Portland-Vancouver-Hillsboro, which are areas in Oregon and Washington. "
        "Y-axis is YYYY-MM, and x-axis is location, we see that around the end of 2021, the growth rate begins to increase significantly. "
        "This area had exponential growth with a fit of 0.86 r2 score, and avg monthly growth rate of 4.8%"
    ])

]),


    # 5) Overall summary
    html.Div(className="findings-section", children=[
        html.H3("Summary", className="subsection-title"),
        html.Div(className="findings-text", children=[
            "From these analysis and visualizations, we can see that both energy usage and charging "
           "sessions is increasing over time. We can see that energy usage is being consumed at almost "
           "exponential rate in the pacific region compared to linear overall in the USA. While focusing " 
           "on the Pacific region, we can see that the most popular charging locations are around Oregon and Washington. "
           "The next step now would be to analyze the difference between Electric and Gas, and predict future trends."
        ])
    ]),

])
