from app import np, go, dash, dcc, html

dash.register_page(__name__, path="/findings") 
layout = html.Div([
    html.H2("Major Findings for EV Growth"),
    html.H3("EV Energy Growth Analysis and Visualization:"),

    #EV sales plot by Iea
    html.H3("EV Sales In USA, generated by IEA:"),
    html.Img(src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/EV_sales_USA_2010-2023IEA.png",
       style={"width": '50%', "height": "auto",  "margin": 'auto 50px' }),
       
    html.P(["In this plot generated by ",
       html.A('IEA', 
       href="https://www.iea.org/data-and-statistics/data-tools/global-ev-data-explorer",
       target="_blank"),
       ", We can see that the number of EV sales has an exponential growth over the years in the USA."
    ],style={'max-width': '50vw'}),



    #Global EV energy history analysis
    html.H3("United States EV Energy History:"),

    html.Div([
       html.Img(src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/global%20energy%20usage%20history.png", 
           style={"width": '25%', "height": "auto", 
              "margin-bottom": '5px', 
              "margin-left": '50px',
              "margin-right": '4px'}
       ),
       html.Img(src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/global%20charging%20session%20history.png", 
           style={"width": '25%', "height": "auto", 
              "margin-bottom": '5px', 
              "margin-left": '5px'}
       )
    ], style={'display': 'flex', 'flex-direction': 'row'}),
       
    html.P("Summary: The (left) plot shows Energy usage history, the (right) plot shows charging session history.",
       style={'max-width': '50vw'}),
    

    html.Img(src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/global%20charging%20session%20and%20energy%20usage%20history.png", 
       style={"width": '50%', "height": "auto",  "margin": 'auto 50px' }),
    html.P("Summary: This plot compares the energy usage and charging session history. "
           "Though they look similar in the 2 plots above, the amount of energy usage is "
           "much higher than the amount of charging sessions. We can see that the energy "
           "usage has increased. Using a linear regression model, we found both charging sessions "
           "and energy usage has an linear growth (confirmed by linear regression with r2 score of 0.902 "
           "and 0.909 respectively). Charging sessions had an avg monthly growth rate of 35.61% while energy increased "
           "by 41.71% each month."
           ,
       style={'max-width': '50vw'}),
    
    
    #pacific region analysis
    html.H3("Further analysis in the Pacific Region:"),
    html.Img(src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/pacific_results/pacific_charging_and_energy_usage.png", 
      style={"width": '50%', "height": "auto",  "margin": 'auto 50px' }),
    html.P(["(Info: History of charging sessions and energy usage in the Pacific region.)",
            html.Br(),
           "Summary: This plot focuses on comparing charging sessions and energy usage in the Pacific region. "
           "Something interesting we found, is that the pacific region has an exponential growth rate, where the exponential "
           "model has an r2 score of 0.9, compared to the linear model with an r2 score of 0.8. This means that the exponential model "
           "fitted better than the linear regression model. While the monthly growth rates we got for charging was around 2.59% and 3.51% " 
           "for energy usage."
           ],
           style={'max-width': '50vw'}
       ),


    #Popular charging locations in the pacific region
    html.H3("Popular Charging Locations in the Pacific Region:"),
    html.Img(src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/pacific_results/pacific_top_charging_locations.png", 
       style={"width": '50%', "height": "auto",  "margin": 'auto 50px' }),
    
    html.P(["(Info: History of charging counts for each location.)",
            html.Br(),
           "Summary: The plot shows that the amount of charging session is increasing over time. "
           "This can highlight the most popular charging locations in the Pacific region. "
           "We can see that the most popular location at the end of 2022 is around the oregon and "
           "washington area in portland-vancouvr-hillsboro. The second most popular location however "
           "is undesigned, which meant the location was obscured for anonymization purposes. But in general," 
           "according to the dataset dictionary, they are not metro areas or areas with to few charging stations. "
           ],
           style={'max-width': '50vw'}
       ),


    html.Img(src="https://storage.googleapis.com/evenergy163.appspot.com/new_results/pacific_results/pacific_heatmap_top_areas.png", 
      style={"width": '50%', "height": "auto",  "margin": 'auto 50px' }),

    html.P(["(Info: Another visualization for popular locations.)",
            html.Br(),
           "Summary: The heatmap shows us over time how much each location charging station usage is increasing or decreasing. "
           "Going down the y-axis, we can closer to the present, we can see the areas get more and more charging records. "
           "(Note): Portland-Vancouver-Hillsboro had an avg monthly growth rate of 3.17% for charging sessions, when comparing linear "
           "and exponential models, the exponential model had an r2 score of 0.858, while the linear model had an r2 score of 0.744. "
           "meaning the exponential model fitted better than the linear regression model. "
           ],
           style={'max-width': '50vw'}
       ),

    html.H3("Summary:"),
    html.P("From these analysis and visualizations, we can see that both energy usage and charging "
           "sessions is increasing over time. We can see that energy usage is being consumed at almost "
           "exponential rate in the pacific region compared to linear overall in the USA. While focusing " 
           "on the Pacific region, we can see that the most popular charging locations are around Oregon and Washington. "
           "The next step now would be to analyze the difference between Electric and Gas, and predict future trends.",
           style={'max-width': '50vw'}),

])